[build]
builder = "nixpacks"

[build.nixpacks]
buildCmd = "cd streamlit && pip install -r requirements.txt"

[deploy]
startCommand = "cd streamlit && streamlit run nav.py --server.port=$PORT --server.address=0.0.0.0"