"""Export the report-writing kit for use outside the pipeline (e.g. Cowork).

The voice loop normally runs through `authoring.write_from_dry`, which composes
the writer prompt from the live constants. When the rewriting happens somewhere
else — a Cowork folder, a browser tab, another model — those same constants have
to be handed over as a file instead.

**Generate, never hand-copy.** A hand-written copy of the guidance is a fourth
place the faithfulness rules live, and the whole reason `prompts.py` exists is
that copies drift. Re-run this script after any change to `WRITER_CONTRACT`,
`WRITER_FAITHFULNESS` or the shared blocks.

    python -m scripts.export_cowork_kit --tegs 4,14,17 --out ~/cowork/teg

Writes, under `--out`:

    base reports/teg_N_dry_draft.md     the facts, flat  (stage 4a output)
    base reports/teg_N_context.json     venue + career/course history + win anatomy
    reporting guidance.md               contract + faithfulness + output rule
    how to run.md                       the prompt to paste, and the protocol

Drop the whole folder somewhere with a `styles/` directory alongside it and the
workflow is self-contained: `how to run.md` says what to paste, `reporting
guidance.md` is what the model reads.

`teg_N_context.json` is close to the `bundle_context="data"` packet: structured
data with the sentence-valued fields stripped, so it supplies material without
supplying phrasing. `notable_milestones` is **kept** by default, unlike the
in-pipeline packet, because it is the only place "defending champion" /
"reigning holder" framing is licensed from and that framing is exactly what the
occasion device wants. Pass `--strict-data` to drop it too.
"""
from __future__ import annotations

import argparse
import json
import os

from teg_analysis.reporting import authoring
from teg_analysis.reporting.story_plan import assemble_bundle


# Mirrors the note `report_around_draft` appends when `plan_scope="none"`. The
# contract block refers to story-plan fields throughout ("the plan's
# `narrative_vehicles`", `must_include_beat_ids`, the per-round angles); without
# this the reader hunts for them and improvises.
NO_PLAN_PREAMBLE = """# Reporting guidance

Generated from the live pipeline constants by `scripts/export_cowork_kit.py`.
Do not edit this file by hand — edit the constants and re-run the script.

## What you have, and what you do not

You are given a **dry draft**: a complete, flat, accurate account of the
tournament, and optionally a **context file** of structured data (venue, career
and per-course history, the anatomy of the win). Your job is to rewrite the dry
draft as a finished report in a supplied voice.

**There is no story plan.** The guidance below refers in places to plan fields —
`narrative_vehicles`, `players[]`, `must_include_beat_ids`, the per-round angles
and headlines. You have none of them. Where a rule refers to a field you have not
been given, disregard that reference and work from the dry draft instead. **Every
structural and faithfulness requirement still stands.**

**Add no facts.** Every hole, score, name, date and margin must come from the dry
draft or the context file. If it is not there, it does not exist.

---

"""

SECTIONS = (
    ("## What the report must be, whatever voice it is written in",
     "WRITER_CONTRACT"),
    ("## Faithfulness — non-negotiable", "WRITER_FAITHFULNESS"),
    ("## Output", "WRITER_OUTPUT_RULE"),
)


# The prompt is part of the kit, not something to remember. A workflow whose
# operating instructions live only in a chat log is not reusable.
HOW_TO_RUN = """# How to run a style trial

Generated by `scripts/export_cowork_kit.py`. One style per run, in a fresh chat.

## The prompt

Replace `<TEG>` and `<STYLE NAME>`, then paste:

```
Rewrite `base reports/teg_<TEG>_dry_draft.md` as a finished tournament report.

VOICE: use the "<STYLE NAME>" entry in `styles/humour styles.md`. That entry is
the complete register. Write in it. Do not blend it with anything else, and do
not fall back on a house style.

Follow `reporting guidance.md` exactly, including THE OCCASION. Read the
archetype off `base reports/teg_<TEG>_context.json` rather than picking the one
you find most appealing.

Every fact must come from the dry draft or the context file. The context file is
data, not phrasing: every sentence in the report is yours to write.

Save the result to `output/teg_<TEG>_<STYLE NAME>.md`.
```

## The protocol

1. **Run a control first.** Same prompt, but "write it in whatever register you
   think fits" instead of a named style. Without a control you cannot tell a
   style's effect from ordinary sampling variation, because the writer re-rolls
   its structural execution on every call.
2. **One style per chat.** Styles bleed when asked for in sequence.
3. **Name the output file after the style.** You will want to read four side by
   side.
4. **Read the openings first.** The occasion device puts the biggest swing in
   the first paragraph, so that is where the styles separate fastest.

## Which base report

Each one exercises a different branch of the occasion device, and a register
that works on one can fall flat on another.

| TEG | Result shape | Archetype the data selects |
|---|---|---|
| 4 | Led by 7 as late as the 8th of R4, and lost it | collapse |
| 14 | Two points, and the rival outplayed him over more rounds | robbery |
| 17 | Eighteen points, built from the front | procession |

## Checking the output

Before judging the prose, check the facts. The failure that matters is the voice
pulling the writer into invention, which reads as confidence rather than error:

- Every score, hole number, name and margin traceable to the dry draft.
- Any total across a stretch of holes adds up exactly.
- The archetype matches the data. A robbery framing on TEG 17 is a factual
  error wearing a costume.
- No "defending champion" or "reigning" claim unless `notable_milestones` in the
  context file says so in as many words.
"""


def build_guidance() -> str:
    parts = [NO_PLAN_PREAMBLE]
    for heading, const in SECTIONS:
        parts.append(heading + "\n\n" + getattr(authoring, const).strip() + "\n")
    return "\n".join(parts)


def _strip(payload: dict, *, keep_milestones: bool) -> dict:
    """Drop the sentence-valued fields, optionally sparing `notable_milestones`.

    The in-pipeline `bundle_context="data"` packet strips all of them. Here the
    milestones are kept by default: they are the ONLY licensed source for
    "defending champion" / "reigning holder" (see `WRITER_FAITHFULNESS`), and
    the occasion device leans on exactly that framing. They are template output,
    not authorial prose, so keeping them costs very little phrasing.
    """
    fields = authoring.DERIVED_PROSE_FIELDS
    if keep_milestones:
        fields = tuple(f for f in fields if f != "notable_milestones")
    return authoring._strip_derived_prose(payload, fields)


def export(tegs: list[int], out_dir: str, *, keep_milestones: bool = True) -> list[str]:
    base = os.path.join(out_dir, "base reports")
    os.makedirs(base, exist_ok=True)
    written = []

    guidance = os.path.join(out_dir, "reporting guidance.md")
    with open(guidance, "w") as f:
        f.write(build_guidance())
    written.append(guidance)

    how_to = os.path.join(out_dir, "how to run.md")
    with open(how_to, "w") as f:
        f.write(HOW_TO_RUN)
    written.append(how_to)

    for teg in tegs:
        dry_path = os.path.join(base, f"teg_{teg}_dry_draft.md")
        with open(dry_path, "w") as f:
            f.write(authoring.load_dry_draft(teg))
        written.append(dry_path)

        bundle, _ = assemble_bundle(teg)
        payload = {k: bundle[k] for k in authoring.BUNDLE_CONTEXT_KEYS if k in bundle}
        payload = _strip(payload, keep_milestones=keep_milestones)
        ctx_path = os.path.join(base, f"teg_{teg}_context.json")
        with open(ctx_path, "w") as f:
            json.dump(payload, f, indent=2, ensure_ascii=False)
        written.append(ctx_path)

    return written


def main() -> None:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--tegs", default="4,14,17",
                    help="comma-separated TEG numbers. The default trio exercises three "
                         "different branches of the occasion device: 4 is a collapse "
                         "(led by 7 at the 8th of R4 and lost it), 14 a robbery "
                         "(attribution 'inherited', 2-point finish), 17 a procession "
                         "(attribution 'built', 18-point margin).")
    ap.add_argument("--out", required=True, help="destination directory")
    ap.add_argument("--strict-data", action="store_true",
                    help="also strip notable_milestones, so the context file has no "
                         "generated sentences at all. Costs the 'defending champion' "
                         "framing, which is licensed only from that field.")
    args = ap.parse_args()

    tegs = [int(t) for t in args.tegs.split(",") if t.strip()]
    for path in export(tegs, args.out, keep_milestones=not args.strict_data):
        print(f"  {os.path.getsize(path):>7,}  {path}")


if __name__ == "__main__":
    main()
