"""Export the report-writing kit for use outside the pipeline (e.g. Cowork).

The voice loop normally runs through `authoring.write_from_dry`, which composes
the writer prompt from the live constants. When the rewriting happens somewhere
else — a Cowork folder, a browser tab, another model — those same constants have
to be handed over as a file instead.

**Generate, never hand-copy.** A hand-written copy of the guidance is a fourth
place the faithfulness rules live, and the whole reason `prompts.py` exists is
that copies drift. Re-run this script after any change to `WRITER_CONTRACT`,
`WRITER_FAITHFULNESS` or the shared blocks.

    python scripts/export_cowork_kit.py --tegs 14,17 --out ~/cowork/teg

Writes, under `--out`:

    base reports/teg_N_dry_draft.md     the facts, flat  (stage 4a output)
    base reports/teg_N_context.json     venue + career/course history + win anatomy
    reporting guidance.md               contract + faithfulness + output rule

`teg_N_context.json` is the `bundle_context="data"` packet: structured data with
every sentence-valued field stripped, so it supplies material without supplying
phrasing. See `authoring.DERIVED_PROSE_FIELDS` for what comes out, and the note
there about "defending champion" framing going with it.
"""
from __future__ import annotations

import argparse
import json
import os

from teg_analysis.reporting import authoring
from teg_analysis.reporting.story_plan import assemble_bundle


# Mirrors the note `report_around_draft` appends when `plan_scope="none"`. The
# contract block refers to story-plan fields throughout ("the plan's
# `narrative_vehicles`", `must_include_beat_ids`, the per-round angles); without
# this the reader hunts for them and improvises.
NO_PLAN_PREAMBLE = """# Reporting guidance

Generated from the live pipeline constants by `scripts/export_cowork_kit.py`.
Do not edit this file by hand — edit the constants and re-run the script.

## What you have, and what you do not

You are given a **dry draft**: a complete, flat, accurate account of the
tournament, and optionally a **context file** of structured data (venue, career
and per-course history, the anatomy of the win). Your job is to rewrite the dry
draft as a finished report in a supplied voice.

**There is no story plan.** The guidance below refers in places to plan fields —
`narrative_vehicles`, `players[]`, `must_include_beat_ids`, the per-round angles
and headlines. You have none of them. Where a rule refers to a field you have not
been given, disregard that reference and work from the dry draft instead. **Every
structural and faithfulness requirement still stands.**

**Add no facts.** Every hole, score, name, date and margin must come from the dry
draft or the context file. If it is not there, it does not exist.

---

"""

SECTIONS = (
    ("## What the report must be, whatever voice it is written in",
     "WRITER_CONTRACT"),
    ("## Faithfulness — non-negotiable", "WRITER_FAITHFULNESS"),
    ("## Output", "WRITER_OUTPUT_RULE"),
)


def build_guidance() -> str:
    parts = [NO_PLAN_PREAMBLE]
    for heading, const in SECTIONS:
        parts.append(heading + "\n\n" + getattr(authoring, const).strip() + "\n")
    return "\n".join(parts)


def export(tegs: list[int], out_dir: str) -> list[str]:
    base = os.path.join(out_dir, "base reports")
    os.makedirs(base, exist_ok=True)
    written = []

    guidance = os.path.join(out_dir, "reporting guidance.md")
    with open(guidance, "w") as f:
        f.write(build_guidance())
    written.append(guidance)

    for teg in tegs:
        dry_path = os.path.join(base, f"teg_{teg}_dry_draft.md")
        with open(dry_path, "w") as f:
            f.write(authoring.load_dry_draft(teg))
        written.append(dry_path)

        bundle, _ = assemble_bundle(teg)
        payload = {k: bundle[k] for k in authoring.BUNDLE_CONTEXT_KEYS if k in bundle}
        payload = authoring._strip_derived_prose(payload)
        ctx_path = os.path.join(base, f"teg_{teg}_context.json")
        with open(ctx_path, "w") as f:
            json.dump(payload, f, indent=2, ensure_ascii=False)
        written.append(ctx_path)

    return written


def main() -> None:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--tegs", default="14,17",
                    help="comma-separated TEG numbers (default: 14,17 — a close "
                         "finish and a procession, the pair worth testing on)")
    ap.add_argument("--out", required=True, help="destination directory")
    args = ap.parse_args()

    tegs = [int(t) for t in args.tegs.split(",") if t.strip()]
    for path in export(tegs, args.out):
        print(f"  {os.path.getsize(path):>7,}  {path}")


if __name__ == "__main__":
    main()
