# GitHub Configuration
# Get this from GitHub: Settings > Developer settings > Personal access tokens > Tokens (classic)
# Make sure it has 'repo' permissions for private repositories
GITHUB_TOKEN = "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"

# Google Sheets Configuration
# These come from your Google Service Account JSON file
# You can get this from Google Cloud Console > APIs & Services > Credentials > Service Accounts
GOOGLE_TYPE = "service_account"
GOOGLE_PROJECT_ID = "maps-1489139675490"
GOOGLE_PRIVATE_KEY_ID = "9fba091753a95f01a46949322e3b1a9fbdd9a0e4"
GOOGLE_PRIVATE_KEY = "-----BEGIN PRIVATE KEY-----\n9fba091753a95f01a46949322e3b1a9fbdd9a0e4\n-----END PRIVATE KEY-----\n"
GOOGLE_CLIENT_EMAIL = "teg-data@maps-1489139675490.iam.gserviceaccount.com"
GOOGLE_CLIENT_ID = "102666565496006119970"
GOOGLE_AUTH_URI = "https://accounts.google.com/o/oauth2/auth"
GOOGLE_TOKEN_URI = "https://oauth2.googleapis.com/token"
GOOGLE_AUTH_PROVIDER_X509_CERT_URL = "https://www.googleapis.com/oauth2/v1/certs"
GOOGLE_CLIENT_X509_CERT_URL = "https://www.googleapis.com/robot/v1/metadata/x509/your_service_account_email%40your_project.iam.gserviceaccount.com"
GOOGLE_UNIVERSE_DOMAIN = "googleapis.com"

# Railway Environment (set to true to simulate Railway environment)
RAILWAY_ENVIRONMENT = "true" 